---
- name: install phpmyadmin
  apt: name=phpmyadmin state=latest

- name: copy dpkg config
  copy: src=phpmyadmin.conf dest=/etc/dbconfig-common/phpmyadmin.conf owner=root group=root mode=0600

- mysql_db: name=phpmyadmin state=import target=/usr/share/doc/phpmyadmin/examples/create_tables.sql.gz

- name: copy phpmyadmin config
  copy: src=config-db.php dest=/etc/phpmyadmin/config-db.php owner=root group=www-data mode=640

- name: setup phpmyadmin user
  mysql_user: name={{ pma_user_name }} password={{ pma_user_password }} priv=*.*:ALL state=present

- name: link phpmyadmin apache config file
  file: src=/etc/phpmyadmin/apache.conf dest=/etc/apache2/conf-enabled/phpmyadmin.conf state=link
