---
- name: configure apache
  copy: src=touch-code.conf dest=/etc/apache2/sites-available/touch-code.conf owner=root group=root mode=0644

- name: enable apache config file
  command: a2ensite touch-code

- name: ensure apache is running
  command: service apache2 restart
