---
- name: configure apache
  copy: src=touch-code dest=/etc/ owner=root group=root mode=0644
  notify:
  - restart apache

- name: ensure apache is running
  service: name=apache2 state=started
  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

