---
- name: configure apache
  copy: src=touch-code.conf dest=/etc/apache2/sites-available/touch-code.conf owner=root group=root mode=0644

- name: enable apache config
  command: a2ensite touch-code

- name: disable default config
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent

- service: name=apache2 state=restarted
