---
- file: path={{ ruby_base_dir }} owner=root group=root state=directory

- name: download ruby {{ ruby_version }}
  get_url: url="http://cache.ruby-lang.org/pub/ruby/2.1/ruby-{{ ruby_version }}.tar.gz"
           dest={{ ruby_archive }}
           sha256sum={{ ruby_sha256sum }}

- name: extract archive
  command: chdir={{ ruby_base_dir }} /bin/tar xvf {{ ruby_archive }} creates={{ ruby_extract_dir }}

- name: configure
  command: chdir={{ ruby_extract_dir }} ./configure --prefix=/usr/local creates=Makefile

- name: make
  command: chdir={{ ruby_extract_dir }} make

- name: make install
  command: chdir={{ ruby_extract_dir }} make install creates=/usr/local/bin/ruby

- name: install bundler
  gem: name=bundler user_install=no
